### ISSUE TITLE
[pf_ring.ko] A little bug in check_free_ring_slot()

### ISSUE THREAD

**Issue by FredChenChwThrox** [ntop/PF_RING#588]
Dear Team:

I was using PF_RING6.4.1 to capture some pkts for analysis, and found that it might miss a pkt when the slots is almost empty. 

I add some debug code in pf_ring.c to trace this issue:
```
static inline int check_free_ring_slot(struct pf_ring_socket *pfr)
{
    u_int64_t remove_off;

    if (pfr->tx.enable_tx_with_bounce && pfr->header_len == long_pkt_header) /* fast-tx enabled */
        remove_off = pfr->slots_info->kernel_remove_off;
    else
        remove_off = pfr->slots_info->remove_off;

    if (pfr->slots_info->insert_off == remove_off)
    {
        u_int64_t queued_pkts;

        /* Both insert and remove offset are set on the same slot.
     * We need to find out whether the memory is full or empty */

        if (pfr->tx.enable_tx_with_bounce && pfr->header_len == long_pkt_header)
            queued_pkts = num_kernel_queued_pkts(pfr);
        else
            queued_pkts = num_queued_pkts(pfr);

        if (queued_pkts >= pfr->slots_info->min_num_slots)
        {
            printk("1 Memory is full insert_off[%llu] remove_off[%llu] total_insert[%llu] total_read[%llu] queued_pkts[%llu]\n"
            , pfr->slots_info->insert_off, remove_off, pfr->slots_info->tot_insert, pfr->slots_info->tot_read, queued_pkts); // I add this line to output the information
            return (0); /* Memory is full */
        }
    }
```
And get this two logs in my test:
```
[153424.833173] 1 Memory is full insert off[6363488] remove off[6363368] total insert[480345918] total read [480345918] queued pkts [18446744073709551615]

[153449.431370] 1 Memory is full insert off[12665512] remove off[12663984] total insert[486523514] total read [486523514] queued pkts[18446744073709551615]
```
As we can see the total_insert is equal to total_read, while the queue_pkts is 18446744073709551615 (It is 0xFFFFFFFFFFFFFFFF).

I guess it might cause by cache coherency problem, maybe we need to add barrier() in some place to fix.

**Comment by cardigliano** [comment]
@FredChenChwThrox what arch are you running?

**Comment by FredChenChwThrox** [comment]
> @FredChenChwThrox what arch are you running?

It's x86, Centos7, 
kernel version 3.10.0-327.el7.x86_64

**Comment by FredChenChwThrox** [comment]
@cardigliano 

Hi Cardigliano:

Good day!
I have read the code, and function check_free_ring_slot() will return "0" in 3 situation:

1. when the "remove_off == insert_off", It means the queue is full or empty.
   "0" will be return only when the queue is full
   
2. When the "remove_off > insert_off", the free space is between insert_off and remove_off,
   "0" will be return when the free space is less than 3 * slot_len.

3. When the "remove_off < insert_off", the free space is seprated into 2 areas: [insert_off, tot_mem] and [0, remove_off].
   It will only check the situation when remove_off == 0, because when remove_off is not 0, if there is no enough space in the high area, the insert_off will be set to 0, and go on with situation 2.
   
Consider if the situation 2 and 3, I think the situation 1 might never happen, because it will stop and drop pkt when there are 3 slots between insert_off and remove_off. 

Maybe we can remove situation 1 to bypass my issue.

My question is: is there other situation that might lead to the queue become full in situation 1?

Thanks
Fred

**Comment by cardigliano** [comment]
@FredChenChwThrox I pushed a patch for this (a safety check to avoid mem coherency issues due to kernel vs userspaces updates), please update to latest 7.6 (stable) or 7.7 (dev). Thank you for your analysis.

**Comment by FredChenChwThrox** [comment]
![pfring_drop_pkt_when_queue_is_empty](https://user-images.githubusercontent.com/15625658/82791626-aea18b80-9ea0-11ea-95ba-241331fba299.png)

@cardigliano Due to some policy restrictions, I can't easily update my pfring to 7.6. I apply your fix on 6.4.1 and found the issue persists. I'll try 7.6 later, but it will take some time.

**Comment by cardigliano** [comment]
@FredChenChwThrox please also apply d882e0eea01af448b79cf1a3ef1f1e0f456e998b

**Comment by FredChenChwThrox** [comment]
Thanks, I'll try it later. @cardigliano

**Comment by FredChenChwThrox** [comment]
Hi Cardigliano:

We have tested the fix in our environment. The issue didn't happen again.
I'll close this issue. Thanks for your kindly help.

Regards
Fred

**Comment by cardigliano** [comment]
Thank you
